---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - prometheus-stack.yaml
  - loki-stack.yaml
configMapGenerator:
  - name: prometheus-stack-values
    files:
      - values.yaml=prometheus-stack-values.yaml
    options:
      disableNameSuffixHash: true
  - name: loki-values
    files:
      - values.yaml=loki-values.yaml
    options:
      disableNameSuffixHash: true
  - name: promtail-values
    files:
      - values.yaml=promtail-values.yaml
    options:
      disableNameSuffixHash: true
