---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - release.yaml
configMapGenerator:
  - name: serviceexample-values
    files:
      - values.yaml
